#거북이 그래픽 모듈 사용
'''
AI소프트웨어과
1학년
1반
박민준
'''
#import turtle as t
import turtle
turtle.shape("turtle")
#8 gack hyong
turtle.color("purple")
turtle.begin_fill()
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.end_fill()
#6 gack hyong
turtle.color("blue")
turtle.begin_fill()
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.end_fill()
#5 gack hyong
turtle.color("green")
turtle.begin_fill()
turtle.forward(100)
turtle.left(72)
turtle.forward(100)
turtle.left(72)
turtle.forward(100)
turtle.left(72)
turtle.forward(100)
turtle.left(72)
turtle.forward(100)
turtle.left(72)
turtle.end_fill()
#4 gack hyong
turtle.color("yellow")
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.end_fill()
#3 gack hyong
turtle.color("red")
turtle.begin_fill()
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(120)
turtle.end_fill()
#2 gack hyong
turtle.color("black")
turtle.begin_fill()
turtle.forward(100)
turtle.left(180)
turtle.forward(100)
turtle.left(180)
turtle.forward(100)
turtle.left(180)
turtle.forward(100)
turtle.left(180)
turtle.end_fill()
